# Site wide configuration

title: Zac Clay
description: Ruby on Rails Developer
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
# url: http://www.zac.im
# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
paginate: 5
paginate_path: "blog/:num/"
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Zac Clay
  email: zacclay@gmail.com
  twitter: mebezac
  github: mebezac
  google:
    ad-client:
    ad-slot:
    ads: false
  bio: Ruby on Rails Developer
  avatar: zac.png # 160x160 px image for author byline
disqus-shortname: zacimblog


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
